version: "2"
services:
  nginx:
    image: nginx:latest
#    depends_on:
#      - fpm
    ports:
      - 80:80
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./project:/var/www/html:rw
#      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./contaners/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
#    volumes_from:
#      - fpm:rw
#    command: nginx -g "daemon off;"
    links:
      - php

  php:
#    image: php:7-fpm
    build:
      context: ./contaners/fpm
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./project:/var/www/html:rw
      - ./contaners/fpm/init.sh:/root/init.sh:ro
    ports:
      - 8000:8000
      - 9001:9001
    expose:
      - "9000"
    links:
      - postgres
#      - rabbitmq
  postgres:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - ./database/postgres:/data/postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: kjshddfg_32sd
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      PGDATA : /data/postgres
#  rabbitmq:
#    image: rabbitmq:3-management
#    expose:
#      - 5672
#      - 15674
#    ports:
#      - "15674:15674"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: rabbit
#      RABBITMQ_DEFAULT_PASS: password